name: agents
networks:
  1panel-network:
    external: true
services:
  agents:
    image: sorc/sandbox-node:24.04
    container_name: pi
    hostname: pi
    restart: always
    networks:
      - 1panel-network
    user: "1000:1000"
    environment:
      - MULTICA_TOKEN=${MULTICA_TOKEN}
      - MULTICA_SERVER_URL=${MULTICA_SERVER_URL}
      - MULTICA_APP_URL=${MULTICA_APP_URL}
      - LOG_LEVEL=info
    volumes:
      - ./home:/home/sorc
      - ./setup:/docker-entrypoint-init.d
      - /datadisk/test:/datadisk/test
      - /datadisk/workspaces:/home/sorc/workspaces
    command: >
      bash -c "source ~/.bashrc && multica daemon start --foreground"
